// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface QuizDB {
    datasetId: string;
    title:     string;
    version:   string;
    createdAt: Date;
    tags:      string[];
    questions: Question[];
    scoring:   Scoring;
}

export interface Question {
    id:          string;
    type:        Type;
    difficulty:  number;
    prompt:      string;
    choices:     Choice[];
    answer:      Answer;
    explanation: string;
}

export interface Answer {
    choiceId?:  ChoiceID;
    choiceIds?: ChoiceID[];
}

export enum ChoiceID {
    A = "A",
    B = "B",
    C = "C",
    D = "D",
}

export interface Choice {
    id:   ChoiceID;
    text: string;
}

export enum Type {
    Multi = "multi",
    Single = "single",
}

export interface Scoring {
    defaultPoints:      number;
    allowPartialCredit: boolean;
}
